# Generated by Django 5.0 on 2025-12-19 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiosDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('DNI', models.CharField(max_length=20, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosdeEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estudio', models.DateTimeField()),
                ('resultado', models.TextField()),
                ('fecha_resultado', models.DateTimeField(auto_now_add=True)),
                ('bioquimico_responsable', models.CharField(max_length=100)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaboratorioMinozzi.estudiosdisponibles')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaboratorioMinozzi.pacientes')),
            ],
        ),
    ]
