# Generated by Django 5.0 on 2025-12-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaboratorioMinozzi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosdeestudios',
            name='resultado',
            field=models.FileField(upload_to='resultados_pdfs/'),
        ),
    ]
