# Generated by Django 5.0 on 2026-01-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaboratorioMinozzi', '0002_alter_resultadosdeestudios_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadosdeestudios',
            name='estudio',
        ),
        migrations.AlterField(
            model_name='resultadosdeestudios',
            name='fecha_estudio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resultadosdeestudios',
            name='fecha_resultado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosdeestudios',
            name='resultado',
            field=models.FileField(upload_to='resultados/'),
        ),
        migrations.AddField(
            model_name='resultadosdeestudios',
            name='estudio',
            field=models.ManyToManyField(to='LaboratorioMinozzi.estudiosdisponibles'),
        ),
    ]
