# Generated by Django 5.0 on 2026-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaboratorioMinozzi', '0004_alter_pacientes_dni_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='DNI',
            new_name='dni',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='telefono',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
